# Generated by Django 3.2.5 on 2021-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='IdCategoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
